In [1]:
!pip install requests

Requirement already satisfied: requests in c:\users\user\anaconda3\lib\site-packages (2.28.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\user\anaconda3\lib\site-packages (from requests) (1.26.14)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\anaconda3\lib\site-packages (from requests) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\anaconda3\lib\site-packages (from requests) (2022.12.7)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\user\anaconda3\lib\site-packages (from requests) (2.0.4)

In [10]:
import requests
from urllib import parse
import pandas as pd

In [11]:
### API 요청 (본인의 키 사용)

In [12]:
# API 요청.(본인의 API 키 사용)
def geocode(address, type='ROAD'):
    result = requests.get("http://api.vworld.kr/req/address?service=address"
        + "&request=getcoord" +"&version2.0" + "&crs=epsg:4326"
        + "&address=" + parse.quote(address) + "&type=" + type
        + "&key=AC370CF9-E544-396F-816A-D6E351AA1324")
    return result

In [13]:
#https://api.vworld.kr/req/address?service=address
#    + &request=getcoord&version=2.0&crs=epsg:4326
#        &address=%ED%9A%A8%EB%A0%B9%EB%A1%9C72%EA%B8%B8%2060
#        &refine=true&simple=false&format=xml&type=road&key=[KEY]

In [14]:
CB_file = pd.read_csv('./data/ch9/CoffeeBean_2024_2.csv',encoding='cp949',  engine='python')

CB_file.head() #작업 내용 확인용 출력

,store,address,phone,address2
0,학동역 DT점,서울시 강남구 학동로 211 1층,02-3444-9973,서울특별시 강남구 학동로 211 1층
1,수서점,서울시 강남구 광평로 280 수서동 724호,02-3412-2326,서울특별시 강남구 광평로 280 수서동 724호
2,차병원점,서울시 강남구 논현로 566 강남차병원1층,02-538-7615,서울특별시 강남구 논현로 566 강남차병원1층
3,강남대로점,서울시 서초구 강남대로 369 1층,02-588-5778,서울특별시 서초구 강남대로 369 1층
4,메가박스점,서울 강남구 삼성동 159 코엑스몰 지하2층,02-6002-3320,서울특별시 강남구 삼성동 159 코엑스몰 지하2층

In [15]:
# 경도, 위도 필드 만들기
CB_file['경도'] = 0.0
CB_file['위도'] = 0.0
CB_file

,store,address,phone,address2,경도,위도
0,학동역 DT점,서울시 강남구 학동로 211 1층,02-3444-9973,서울특별시 강남구 학동로 211 1층,0.0,0.0
1,수서점,서울시 강남구 광평로 280 수서동 724호,02-3412-2326,서울특별시 강남구 광평로 280 수서동 724호,0.0,0.0
2,차병원점,서울시 강남구 논현로 566 강남차병원1층,02-538-7615,서울특별시 강남구 논현로 566 강남차병원1층,0.0,0.0
3,강남대로점,서울시 서초구 강남대로 369 1층,02-588-5778,서울특별시 서초구 강남대로 369 1층,0.0,0.0
4,메가박스점,서울 강남구 삼성동 159 코엑스몰 지하2층,02-6002-3320,서울특별시 강남구 삼성동 159 코엑스몰 지하2층,0.0,0.0
...,...,...,...,...,...,...
273,송파헬리오시티점,서울시 송파구 송파대로 345 ( 헬리오시티상가 3블럭 A동 B1층 22호 ),02-777-3363,서울특별시 송파구 송파대로 345 ( 헬리오시티상가 3블럭 A동 B1층 22호 ),0.0,0.0
274,청계천을지로점,서울 중구 남대문로10길 33 1F,02-723-1771,서울특별시 중구 남대문로10길 33 1F,0.0,0.0
275,서초중앙로점,"서울시 서초구 서초중앙로 209, 해성빌딩 1층",02-537-2992,"서울특별시 서초구 서초중앙로 209, 해성빌딩 1층",0.0,0.0
276,일산동구청점,경기도 고양시 일산동구 정발산로 38,031-903-3989,경기도 고양시 일산동구 정발산로 38,0.0,0.0
277,부산화명수정역점,"부산광역시 북구 학사로 8 (화명동 2312), 크리스탈타워 2층 201~202호",051-361-3370,"부산광역시 북구 학사로 8 (화명동 2312), 크리스탈타워 2층 201~202호",0.0,0.0

In [16]:
# 각 주소마다 API 요청
for i in range(len(CB_file)):
    result = None
    coord_x = coord_y = 0.0
    result = geocode(CB_file.at[i, 'address2']).json()
    if result['response']['status'] != 'NOT_FOUND':
        coord_x = result['response']['result']['point']['x']
        coord_y = result['response']['result']['point']['y']
    else:    # 도로명 주소로 못 찾을 시 지번 주소로 찾기
        result = geocode(CB_file.at[i, 'address2'], 'PARCEL').json()
        if result['response']['status'] != 'NOT_FOUND':
            coord_x = result['response']['result']['point']['x']
            coord_y = result['response']['result']['point']['y']
        else: 
            continue
    
    CB_file.at[i, '경도'] = round(float(coord_x), 4)
    CB_file.at[i, '위도'] = round(float(coord_y), 4)

In [17]:
CB_file

,store,address,phone,address2,경도,위도
0,학동역 DT점,서울시 강남구 학동로 211 1층,02-3444-9973,서울특별시 강남구 학동로 211 1층,127.0321,37.5147
1,수서점,서울시 강남구 광평로 280 수서동 724호,02-3412-2326,서울특별시 강남구 광평로 280 수서동 724호,127.1031,37.4873
2,차병원점,서울시 강남구 논현로 566 강남차병원1층,02-538-7615,서울특별시 강남구 논현로 566 강남차병원1층,127.0345,37.5068
3,강남대로점,서울시 서초구 강남대로 369 1층,02-588-5778,서울특별시 서초구 강남대로 369 1층,127.0282,37.4957
4,메가박스점,서울 강남구 삼성동 159 코엑스몰 지하2층,02-6002-3320,서울특별시 강남구 삼성동 159 코엑스몰 지하2층,127.0588,37.5126
...,...,...,...,...,...,...
273,송파헬리오시티점,서울시 송파구 송파대로 345 ( 헬리오시티상가 3블럭 A동 B1층 22호 ),02-777-3363,서울특별시 송파구 송파대로 345 ( 헬리오시티상가 3블럭 A동 B1층 22호 ),127.1025,37.4977
274,청계천을지로점,서울 중구 남대문로10길 33 1F,02-723-1771,서울특별시 중구 남대문로10길 33 1F,126.9845,37.5678
275,서초중앙로점,"서울시 서초구 서초중앙로 209, 해성빌딩 1층",02-537-2992,"서울특별시 서초구 서초중앙로 209, 해성빌딩 1층",127.0118,37.5003
276,일산동구청점,경기도 고양시 일산동구 정발산로 38,031-903-3989,경기도 고양시 일산동구 정발산로 38,126.7731,37.6567
277,부산화명수정역점,"부산광역시 북구 학사로 8 (화명동 2312), 크리스탈타워 2층 201~202호",051-361-3370,"부산광역시 북구 학사로 8 (화명동 2312), 크리스탈타워 2층 201~202호",129.0087,35.2241

In [18]:
CB_file.to_csv('./data/ch9/CB_geoAPI.shp_2024_2.csv',encoding='CP949', index = False)